baseURL = 'https://antonrademaker.github.io/'
locale = 'en-us'
title = 'Anton Rademaker'
enableRobotsTXT = true

[params]
author = 'Anton Rademaker'
description = 'Anton Rademaker is a Software Architect / Lead Engineer at ilionx, working across software architecture, engineering, and data in mostly the Microsoft ecosystem.'

[markup.goldmark.renderer]
unsafe = false

[markup.highlight]
noClasses = false
style = 'github'

[outputs]
home = ['HTML']